#include "fp.h"
#include <string.h>
void fp_inv_own(fp *b, fp const *a)
{
    fp t[15], tt;
    int i;
    /*
t[0] := a^3;
t[1] := a^5;
t[2] := a^7;
t[3] := a^9;
t[4] := a^11;
t[5] := a^13;
t[6] := a^15;
t[7] := a^17;
t[8] := a^19;
t[9] := a^21;
t[10] := a^23;
t[11] := a^25;
t[12] := a^27;
t[13] := a^29;
t[14] := a^31;
*/  
    fp_sq2(&tt, a);
    fp_mul3(&t[0], &tt, a );//a^3
    for(i = 1; i <=14 ; i++)
        fp_mul3(&t[i], &tt, &t[i-1]);
    
    tt = t[11];
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[12]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[3]);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[13]);
    for (i=0; i < 7; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[6]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[13]);
    for (i=0; i < 11; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[14]);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[8]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[14]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[14]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[11]);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[9]);
    for (i=0; i < 3; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[0]);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[5]);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[9]);
    for (i=0; i < 3; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[2]);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[14]);
    for (i=0; i < 7; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[8]);
    for (i=0; i < 7; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[3]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[9]);
    for (i=0; i < 3; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[1]);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[4]);
    for (i=0; i < 2; i++) fp_sq2(&tt, &tt);
    fp_mul3(&tt, &tt, a);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3(&tt, &tt, a);
    for (i=0; i < 10; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[13]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[13]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[10]);
    for (i=0; i < 7; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[7]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[0]);
    for (i=0; i < 4; i++) fp_sq2(&tt, &tt);
    fp_mul3(&tt, &tt, a);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[3]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[5]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[14]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[14]);
    for (i=0; i < 3; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[2]);
    for (i=0; i < 4; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[0]);
    for (i=0; i < 7; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[5]);
    for (i=0; i < 7; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[8]);
    for (i=0; i < 7; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[7]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[11]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[2]);
    for (i=0; i < 7; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[12]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[8]);
    for (i=0; i < 4; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[5]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[9]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[7]);
    for (i=0; i < 4; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[4]);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[9]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[8]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[14]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[5]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[9]);
    for (i=0; i < 10; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[13]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[7]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[11]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[11]);
    for (i=0; i < 1; i++) fp_sq2(&tt, &tt);
    fp_mul3(&tt, &tt, a);
    for (i=0; i < 9; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[11]);
    for (i=0; i < 1; i++) fp_sq2(&tt, &tt);
    fp_mul3(&tt, &tt, a);
    for (i=0; i < 10; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[14]);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[4]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[8]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[11]);
    for (i=0; i < 7; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[10]);
    for (i=0; i < 9; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[8]);
    for (i=0; i < 4; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[3]);
    for (i=0; i < 9; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[12]);
    for (i=0; i < 4; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[6]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[7]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[10]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[9]);
    for (i=0; i < 4; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[3]);
    for (i=0; i < 4; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[1]);
    for (i=0; i < 9; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[5]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[7]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[10]);
    for (i=0; i < 11; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[12]);
    for (i=0; i < 4; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[3]);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[1]);
    for (i=0; i < 7; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[11]);
    for (i=0; i < 3; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[2]);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[12]);
    for (i=0; i < 3; i++) fp_sq2(&tt, &tt);
    fp_mul3(&tt, &tt, a);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[6]);
    fp_sq1(&tt);
    fp_sq1(&tt);
    fp_sq1(&tt);
    fp_mul3(b, &tt, a);
}

void fp_sqr_own(fp *b, fp const *a)
{
    fp t[15], tt;
    int i;
    
    /*
t[0] := a^3;
t[1] := a^5;
t[2] := a^7;
t[3] := a^9;
t[4] := a^11;
t[5] := a^13;
t[6] := a^15;
t[7] := a^17;
t[8] := a^19;
t[9] := a^21;
t[10] := a^23;
t[11] := a^25;
t[12] := a^27;
t[13] := a^29;
t[14] := a^31;
*/  fp_sq2(&tt, a);
    fp_mul3(&t[0], &tt, a );//a^3
    for(i = 1; i <=14 ; i++)
        fp_mul3(&t[i], &tt, &t[i-1]);
    
    tt = t[11];
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[12]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[3]);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[13]);
    for (i=0; i < 7; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[6]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[13]);
    for (i=0; i < 11; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[14]);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[8]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[14]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[14]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[11]);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[9]);
    for (i=0; i < 3; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[0]);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[5]);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[9]);
    for (i=0; i < 3; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[2]);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[14]);
    for (i=0; i < 7; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[8]);
    for (i=0; i < 7; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[3]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[9]);
    for (i=0; i < 3; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[1]);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[4]);
    for (i=0; i < 2; i++) fp_sq2(&tt, &tt);
    fp_mul3(&tt, &tt, a);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3(&tt, &tt, a);
    for (i=0; i < 10; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[13]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[13]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[10]);
    for (i=0; i < 7; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[7]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[0]);
    for (i=0; i < 4; i++) fp_sq2(&tt, &tt);
    fp_mul3(&tt, &tt, a);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[3]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[5]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[14]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[14]);
    for (i=0; i < 3; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[2]);
    for (i=0; i < 4; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[0]);
    for (i=0; i < 7; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[5]);
    for (i=0; i < 7; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[8]);
    for (i=0; i < 7; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[7]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[11]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[2]);
    for (i=0; i < 7; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[12]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[8]);
    for (i=0; i < 4; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[5]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[9]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[7]);
    for (i=0; i < 4; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[4]);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[9]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[8]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[14]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[5]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[9]);
    for (i=0; i < 10; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[13]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[7]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[11]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[11]);
    for (i=0; i < 1; i++) fp_sq2(&tt, &tt);
    fp_mul3(&tt, &tt, a);
    for (i=0; i < 9; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[11]);
    for (i=0; i < 1; i++) fp_sq2(&tt, &tt);
    fp_mul3(&tt, &tt, a);
    for (i=0; i < 10; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[14]);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[4]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[8]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[11]);
    for (i=0; i < 7; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[10]);
    for (i=0; i < 9; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[8]);
    for (i=0; i < 4; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[3]);
    for (i=0; i < 9; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[12]);
    for (i=0; i < 4; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[6]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[7]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[10]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[9]);
    for (i=0; i < 4; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[3]);
    for (i=0; i < 4; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[1]);
    for (i=0; i < 9; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[5]);
    for (i=0; i < 6; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[7]);
    for (i=0; i < 5; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[10]);
    for (i=0; i < 11; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[12]);
    for (i=0; i < 4; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[3]);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[1]);
    for (i=0; i < 7; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[11]);
    for (i=0; i < 3; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[2]);
    for (i=0; i < 8; i++) fp_sq2(&tt, &tt);
    fp_mul3( &tt, &tt, &t[12]);
    for (i=0; i < 3; i++) fp_sq2(&tt, &tt);
    fp_mul3(&tt, &tt, a);
    for (i=0; i < 9; i++) fp_sq2(&tt, &tt);
    fp_mul3( b , &tt, &t[14]);

}


bool isSquare(fp const *a)
{
    fp b;
    fp_sqr_own(&b, a);
    fp_sq1(&b);
    if (memcmp(&b, a, sizeof(fp)) )
        return(1);
    else
        return(0);
}
